### ISSUE TITLE
Proxmox manual install guide (this is a non-issue issue)

### ISSUE THREAD

**Issue by russkinz** [ironicbadger/pms-wiki#107]
Hello!

I hate being "that guy" and I know Soon is just whenever you get to it, and you probably have a heap of other stuff on the go - but any guideline on when (or if) you'll have a chance to pull together the Proxmox manual install guide? I'm happy to be a beta tester if that would be helpful... 

If it's not going to be a thing or it's going to be a while off, I'll just bite the bullet and wing it, but I do like having a good example to refer to!

Presumably it's not _vastly_ different to the Ubuntu build (other than some stuff being prebuilt due to the nature of Proxmox etc) so I could use that as a exemplar?

**Comment by tindolt** [comment]
I would also like the guide as well, does it help if we throw money at the solution? haha

**Comment by OptimalGrammar** [comment]
+1 interested in the Proxmox manual guide. Also willing to beta test!

**Comment by russkinz** [comment]
I bit the bullet and did my own version. I'm not sure if it's good, best practice, or even stable... and I didn't document it at all, but I might try find some time to do that and will let you know. I pulled inspiration from multiple sources and would be gathering it all into one place...

**Comment by tindolt** [comment]
Yes please would like to see.

**Comment by caltemus** [comment]
I'm also quite interested in the Proxmox build guide. It's a bit frustrating reading through all of the reasoning behind Proxmox being the better implementation then getting to the guide page only for it to be empty. Going through the ubuntu build guide now.

**Comment by ironicbadger** [comment]
Proxmox is based on Debian which is mostly equivalent to Ubuntu anyways. Following the primary Ubuntu guide will get you there. TBH, I think the solution is just to rename the articles because they're so similar in content anyways.

**Comment by DoctorOctagonapus** [comment]
> Proxmox is based on Debian which is mostly equivalent to Ubuntu anyways. Following the primary Ubuntu guide will get you there. TBH, I think the solution is just to rename the articles because they'd be so similar in content anyways.

That's reassuring! I'm in the early stages of a Proxmox build now and it's all gone smoothly from following the Ubuntu guide so far. I did have to change the Proxmox repos to the non-subscription ones before apt would work, if there are any other differences I'll note them down.

**Comment by ironicbadger** [comment]
First thing I do now on a fresh Proxmox install is "fix" the repos etc using these proxmox helper scripts.

https://helper-scripts.com/scripts?id=Proxmox+VE+Post+Install

**Comment by bedar89** [comment]
> Proxmox is based on Debian which is mostly equivalent to Ubuntu anyways. Following the primary Ubuntu guide will get you there. TBH, I think the solution is just to rename the articles because they'd be so similar in content anyways.

I do understand what you're saying and agree that a lot is the same. But I still find it hard to wrap my head around where I should install/configure what. In the Ubuntu installation you suddenly start working with Docker. But I thought I had to organize my disks in the PVE itself. So I don't think it's wise to install Docker on the pve host. 

Long story short, if you still have the time to write the article for Proxmox users, it would be much appreciated!

**Comment by OptimalGrammar** [comment]
> > Proxmox is based on Debian which is mostly equivalent to Ubuntu anyways. Following the primary Ubuntu guide will get you there. TBH, I think the solution is just to rename the articles because they'd be so similar in content anyways.
> 
> I do understand what you're saying and agree that a lot is the same. But I still find it hard to wrap my head around where I should install/configure what. In the Ubuntu installation you suddenly start working with Docker. But I thought I had to organize my disks in the PVE itself. So I don't think it's wise to install Docker on the pve host.
> 
> Long story short, if you still have the time to write the article for Proxmox users, it would be much appreciated!

I believe you're referring to the part of the guide where we install Snapraid. This is the bit where I'm struggling to see how the Ubuntu guide applies to Proxmox,

**Comment by iqatrophie** [comment]
I was so invested reading up on the 'Perfect Media Server' and now am left hanging for the Proxmox install guide. According to archive.org it's 'Coming soon ™' since September of last year. Is there still a chance it's coming or have you completely switched to NIX OS and/or don't find the time?

I would totally understand if priorities have shifted. No hard feelings. I just want to know if it makes sense to hold the hope up or better move on. :)

**Comment by russkinz** [comment]
> I was so invested reading up on the 'Perfect Media Server' and now am left hanging for the Proxmox install guide. According to archive.org it's 'Coming soon ™' since September of last year. Is there still a chance it's coming or have you completely switched to NIX OS and/or don't find the time?
> 
> I would totally understand if priorities have shifted. No hard feelings. I just want to know if it makes sense keep hope alive or better move on. :)

Hey, I found working through the Ubuntu steps worked with Proxmox for me - but using the Proxmox Helper Scripts (rip tteck) for the apps. It's mostly command line and Ubuntu and Proxmox share a common ancestor (Debian).

**Comment by Paulie420** [comment]
So what happened??

**Comment by iqatrophie** [comment]
Thanks for the tip. I'm currently reading up on the Manual Ubuntu Installation. I'm still trying to figure out the storage aspect whether it's better to passthrough HDDs to a NAS VM or run it straight from within Proxmox. Don't understand the implications and whether I'll run into problems with LXC's or Docker containers having access to the storage space. My goal is some small 4-bay NAS system using something similar to an UNRAID array (HDD spindown) because I want it to be energy efficient without paying the costly yearly fee/subscription for UNRAID. That's why I landed at Proxmox, mergerfs and SNAPRAID respectively 'PMS'

Unfortunately I'm short on time at the moment because of Chrismas preparations. ;)

> ... but using the Proxmox Helper Scripts (rip tteck)

I really tried to look out for helper scripts with the name "rip" and "tteck" only to stumble upon the tragic story of tteck. Really heartbreaking. :(

**Comment by allfab** [comment]
Hi,
I set up my NAS last winter and I read a lot of documentation, especially that of the Perfect Media Server. I was in the same questioning about the configuration/installation of my NAS. I created a site in the same vein as https://perfectmediaserver.com/ in order to set my thoughts and see things more clearly. I would also like to thank IronicBadger for sharing his configuration without which I would never have taken the plunge and on which I relied heavily. Here is the link to my doc (in French - https://perfecthomelab.allfabox.fr/). I made the techno choice to start with a machine on Proxmox installed on 2 NVME disks and ZFS mirror + 2 18TB disks (one for parity, the other for data) on which I installed mergerFS and Snapraid directly in bare metal.

On my Proxmox, I have 7-8 LXC containers on which Docker is installed and which run my services (Jellyfin, Navidrome, Traefik, Portainer, Dozzle, Nextcloud and Onlyoffice and applications such as Homepage, etc.). What is interesting with LXC containers is that you can mount "volumes" (folders) directly on the container of the host machine (Proxmox) to the LXC container. This allows, for example, to mount your video/music library which is on a disk fusion such as mergerFS in the container.

I also wrote my infrastructure in a GitHub repository with Ansible: https://github.com/allfab/infrastructure

I hope I have shed some light on your idea of ​​mounting your NAS.

Enjoy reading,
Allfab

**Comment by ironicbadger** [comment]
Done!

https://perfectmediaserver.com/03-installation/manual-install-proxmox/

**Comment by iqatrophie** [comment]
Wow, thanks @ironicbadger for this nice christmas present. :smiley: :christmas_tree: :gift:
