### ISSUE TITLE
Please go ahead and fix your Dockerfile and requirements.txt

### ISSUE THREAD

**Issue by evrial** [ironicbadger/pms-wiki#110]
This is pathetic

**Comment by RealOrangeOne** [comment]
What exactly is broken about them?

If you're going to be rude, at least have the decency to give some detail as to _why_ it's "pathetic"

**Comment by RealOrangeOne** [comment]
This uses the insiders version of `mkdocs-material`, which is private. So you won't be able to build the container sadly. I suspect the reason your build is failing is because there's something in the configuration which depends (or at least assumes) it's running on the insiders build. Sure, they're annoying, and make running a full local build difficult (or impossible perhaps without some TLC), but I wouldn't call them "pathetic".

**Comment by evrial** [comment]
In first case the DNS has no A record, in second that's not my business, it is what it is 🤷‍♀️

**Comment by ironicbadger** [comment]
It's an insiders build, as orange says. This is not a public image, go have a word with upstream if that is a problem to you.

Second, that is a private git server running in my house behind Tailscale, so you won't be able to access it (by design).

**Comment by evrial** [comment]
Ok thanks, as I expected.
