### ISSUE TITLE
Docker installation on host or VM

### ISSUE THREAD

**Issue by mhriemers** [IronicBadger/pms-wiki#7]
Is Docker installed on the host itself or inside a Proxmox VM/unprivileged LXC? I found [this](https://www.servethehome.com/creating-the-ultimate-virtualization-and-container-setup-with-management-guis/) article on ServeTheHome that deemed the former method **not recommend for production**. See also [this](https://www.reddit.com/r/Proxmox/comments/g3wozs/best_way_to_run_docker_in_proxmox/) Reddit post. 

Running on the host itself makes access to the MergerFS pool a lot simpler, but I’m worried about the security issues some Reddit users brought up. Running inside KVM requires an NFS share which results in extra overhead (related to #6). Running inside LXC does allow for host directory mounts but the storage driver needs to be changed to overlay(2). I’m curious what your current setup looks like. 

As a side note, I’m currently in the process of setting up Proxmox + Docker + MergerFS + SnapRaid using your guides as a starting point for my perfect home media server. If you want, I can contribute with PR’s containing my findings along the way.

**Comment by IronicBadger** [comment]
It really depends on how you want to use this system. If you're just looking to store some files and run a few containers then a hypervisor might be a layer of added complexity that you just don't need.

For most people, Proxmox is probably unnecessary.

I have found a lot value from virtualising my media server though. Snapshots, portability and separation being the key reasons. Virtualising the system that contains all my "stuff" allows the hypervisor to remain clean and operate reliably.

You might be the right fit for virtualising via Proxmox if you want to run more than one major service on the same hardware. AdGuard Home, Home Assistant, Blue Iris and PMS for example will all comfortably fit onto a single system with 64GB RAM.

**Comment by afraazali** [comment]
Apologies for resurrecting an old issue. Recently on your blog, I've read that you've moved to installing docker containers on the proxmox host instead of inside a Ubuntu VM. Will this be the recommended approach going forward?

I'm building a new server, and was going to follow the PMS wiki using Ubuntu, with a couple of changes:

 * Using mergerfs within docker
 * Using Ubuntu server instead of desktop

My current server is Ubuntu desktop and everything (wireguard server, adguard, jellyfin and the *arrs) is run in containers. I have HomeAssistant running VirtualBox. Ideally I'd like to pass the iGPU to Jellyfin for transcoding, but then I read that with the later intel chipsets this might not be possible with Proxmox. Is this correct? I'd be using an 11400.

I was thinking to install Proxmox and create 4 VMs:

* HomeAssistant
* Adguard - This would be moved from a container to a VM
* Ubuntu Server - And then run docker in here to run all my containers
* Windows - For light gaming

I read both blog posts on gvt-g and I think that route isn't for me. Ideally I'd like to use the iGPU for some light gaming in Windows. Would this be possible with the above setup, or am I better either:

* Doing docker on the proxmox host, and creating 3 VMs (Adguard, HomeAssistant, Windows)
* Going with a Ubuntu server install
