### ISSUE TITLE
No RSS/ATOM feed?

### ISSUE THREAD

**Issue by rogierlommers** [ironicbadger/pms-wiki#87]
You don't support RSS/atom for feed crawling?
Why not? #living-the-rss-life

**Comment by RealOrangeOne** [comment]
An RSS feed for a wiki site doesn't make much sense, as it's the current state of the content which matters most, rather than it being a list of content like a blog might be.

If you want a feed of changes, you can subscribe to the feed of commits: https://github.com/ironicbadger/pms-wiki/commits/main.atom

With all that said, there is now a blog, which it'd be nice to get a feed for. Seems it's [supported by mkdocs-material](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#rss)

**Comment by ironicbadger** [comment]
I will enable the RSS for the blog, but its low on the priorities.

**Comment by rogierlommers** [comment]
I don't know the CMS you're using, but your initial comment already made sense to me.
(using Github's RSS feature to inform me when you make a change to your site)

**Comment by ironicbadger** [comment]
see #92
